// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brmnahjqutjwhhmsvjnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJybW5haGpxdXRqd2hobXN2am53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDg4NzcsImV4cCI6MjA3MDYyNDg3N30.KKmTJgo8oatBgZ5wD63D80LYuQ-b2EnAVz4KVyAG_BU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});